#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

define('__CAKES__', __DIR__ . DIRECTORY_SEPARATOR);

use Symfony\Component\Console\Application;
use App\Command\CreateCakeReportCommand;

$application = new Application();
$application->add(new CreateCakeReportCommand());
$application->run();
